### ISSUE TITLE
Offer monadic Blaze-style interface for writing VTrees

### ISSUE THREAD

**Issue by garyb** [purescript-contrib/purescript-virtual-dom#2]

**Comment by fluffynukeit** [comment]
The more I use vtree, the more convinced I am that a vtree DSL should be a separate project, akin to how virtual-hyperscript is a different project than virtual-dom (even though they are in the same repo).  There are lots of opinionated ways to design an interface that is easy to use and hides all the little quirks of building vtrees manually.

**Comment by garyb** [comment]
Agreed :) I changed my mind a bit about the direction of this from when I first started working on it - as mentioned in your `options` PR, I think it's probably more useful to have this as a low level thing that hopefully other people will build on top of.

@bodil's `smoulder` had a `virtual-dom` renderer until recently, that could be revived, and @paf31 has `scrap-your-markup` which would also be well suited to a `virtual-dom` interpreter at some point.
